name: Firmware CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - "firmware/**"
  pull_request:
    paths:
      - "firmware/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Cache PlatformIO
        uses: actions/cache@v6
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
          key: pio-${{ runner.os }}-${{ hashFiles('firmware/platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Install PlatformIO
        run: pip install platformio==6.1.16

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc make

      - name: Run Build Script
        working-directory: firmware/scripts
        run: bash build.sh

      - name: Run Test Script
        working-directory: firmware/scripts
        run: bash run-tests.sh
